--Case Statement
BEGIN
	UPDATE EMPLOYEES SET COMMISSION_PCT = CASE
	WHEN COMMISSION_PCT > 0.14 THEN COMMISSION_PCT * 0.10 
	WHEN COMMISSION_PCT > 0.14 AND COMMISSION_PCT < 0.15 THEN COMMISSION_PCT * 0.10 
	ELSE COMMISSION_PCT * 0.2
	END;
END;
/
